/**
 * Auto FAQ pages — 15 essential auto insurance questions with real answers.
 * Used for /auto/faqs/<slug>/ pages.
 */

export const AUTO_FAQS = [
  {
    slug: "what-does-car-insurance-cost",
    question: "What does car insurance cost?",
    category: "Pricing",
    title: "What Does Car Insurance Cost? Real-Rate Averages 2026",
    description: "Real-rate averages for car insurance by state, driver age, coverage level, and credit profile.",
    answer: "The national average for full-coverage auto insurance in 2026 is approximately $1,750/year, or about $146/month. State-minimum liability-only coverage averages around $620/year ($52/month).",
    breakdown: [
      { factor: "Driver age 16-25", impact: "Often 2-3x the average — young drivers are statistically high-risk" },
      { factor: "Driver age 35-55", impact: "Usually below average — peak experience years" },
      { factor: "Senior drivers (65+)", impact: "Slight increase but still close to average" },
      { factor: "Credit-based insurance score", impact: "Can swing rates ±40% (banned in CA, HI, MA)" },
      { factor: "ZIP code", impact: "Major factor — urban density and theft rate matter" },
      { factor: "Driving record", impact: "One ticket adds 15-25%; one at-fault accident adds 30-50%" },
    ],
    shoppingTip: "Get quotes from at least 3-4 carriers every renewal. Loyalty doesn't pay in auto insurance — long-time customers often pay more than new customers for the same coverage.",
  },
  {
    slug: "how-is-auto-insurance-calculated",
    question: "How is auto insurance calculated?",
    category: "Pricing",
    title: "How Is Auto Insurance Calculated? The Real Math Explained",
    description: "How insurers actually calculate your auto insurance premium. The factors that matter most, and what you can change.",
    answer: "Auto insurance premiums are calculated based on a combination of risk factors — your personal driving profile, your vehicle, your location, and your credit history. Each carrier weights these factors slightly differently, which is why the same person can get quotes that vary by 50% or more.",
    breakdown: [
      { factor: "Driving record", impact: "Tickets, accidents, DUIs — biggest single factor for most drivers" },
      { factor: "Age and experience", impact: "Young/inexperienced drivers pay 2-3x more than 35-55 age group" },
      { factor: "Vehicle make/model", impact: "Theft rate, repair cost, and safety scores affect rates" },
      { factor: "Location (ZIP code)", impact: "Urban density, theft, and accident frequency by area" },
      { factor: "Coverage limits", impact: "Higher limits and lower deductibles raise premium" },
      { factor: "Credit-based insurance score", impact: "Allowed in 47 states (banned in CA, HI, MA)" },
      { factor: "Annual mileage", impact: "Low-mileage drivers (under 7,500/yr) often qualify for discounts" },
    ],
    shoppingTip: "The fastest way to reduce your premium without changing your driving profile: raise your deductible, drop collision/comprehensive on older vehicles, bundle with home/renters, and shop competing carriers every renewal.",
  },
  {
    slug: "how-much-car-insurance-do-i-need",
    question: "How much car insurance do I need?",
    category: "Coverage",
    title: "How Much Car Insurance Do I Need? Coverage Recommendations",
    description: "How to figure out the right coverage limits for your situation — beyond just state minimums.",
    answer: "Most experts recommend at least 100/300/100 in liability coverage — significantly more than what most states require as minimums. For high-value assets or high-net-worth situations, 250/500/250 plus an umbrella policy is more appropriate.",
    breakdown: [
      { factor: "Minimum legal coverage", impact: "Varies by state, usually inadequate for serious accidents" },
      { factor: "Recommended: 100/300/100", impact: "Covers most accidents involving multiple parties" },
      { factor: "High-net-worth: 250/500/250 + umbrella", impact: "Protects significant assets from lawsuits" },
      { factor: "Collision/comprehensive", impact: "Required by lenders; optional once paid off" },
      { factor: "UM/UIM", impact: "Match your liability limits — critical for serious injury claims" },
      { factor: "Gap insurance", impact: "Important for new car loans and leases (first 2-3 years)" },
    ],
    shoppingTip: "Don't just buy state minimums to save money — the 'savings' could cost you your home or retirement savings if you're at fault in a serious accident. The premium difference between state-minimum and 100/300/100 is often less than $200/year.",
  },
  {
    slug: "is-car-insurance-required",
    question: "Is car insurance required?",
    category: "Legal",
    title: "Is Car Insurance Required? State Requirements 2026",
    description: "Where car insurance is legally required (almost everywhere), what proof you need, and the penalties for driving without it.",
    answer: "Yes, car insurance is required in 49 out of 50 US states. Only New Hampshire doesn't require it, though drivers there must prove financial responsibility if they have an at-fault accident.",
    breakdown: [
      { factor: "All states except NH", impact: "Require at least liability coverage" },
      { factor: "New Hampshire", impact: "Requires financial responsibility, not specifically insurance" },
      { factor: "Penalties for no insurance", impact: "Fines, license suspension, vehicle impoundment" },
      { factor: "Repeat offenses", impact: "Can result in jail time and SR-22 filing requirement" },
    ],
    shoppingTip: "Even if you don't drive your car often, you need insurance as long as it's registered and on the road. Some states require continuous coverage and will suspend your registration if your insurance lapses.",
  },
  {
    slug: "can-i-cancel-car-insurance-anytime",
    question: "Can I cancel my car insurance anytime?",
    category: "Policies",
    title: "Can I Cancel My Car Insurance Anytime?",
    description: "When and how to cancel auto insurance — and the consequences of letting it lapse.",
    answer: "Yes, you can cancel your auto insurance policy at any time. But cancellation has consequences — if you still have a vehicle registered, you need continuous coverage to comply with state law and avoid registration suspension.",
    breakdown: [
      { factor: "Before switching carriers", impact: "Don't cancel old policy until new one is active — gaps cause issues" },
      { factor: "Prorated refund", impact: "Most carriers refund unused premium" },
      { factor: "Lapses in coverage", impact: "Cause significant rate increases when re-insuring (often 20-40%)" },
      { factor: "Registration", impact: "Most states require continuous coverage for any registered vehicle" },
    ],
    shoppingTip: "When switching carriers, always have the new policy active before canceling the old one. Most insurers can backdate the start date if needed — a one-day overlap costs $5-10 and prevents lapse penalties.",
  },
  {
    slug: "does-credit-score-affect-car-insurance",
    question: "Does credit score affect car insurance rates?",
    category: "Pricing",
    title: "Does Credit Score Affect Car Insurance Rates?",
    description: "How credit-based insurance scores work, where they're used, and how to improve them.",
    answer: "In 47 of 50 states, yes — carriers can use a credit-based insurance score to set your rate. The states that ban this practice are California, Hawaii, and Massachusetts. Credit score can swing your rate by 20-50% in states where it's allowed.",
    breakdown: [
      { factor: "States banning credit", impact: "California, Hawaii, Massachusetts" },
      { factor: "Credit-based insurance score", impact: "Not your FICO score, but uses similar data" },
      { factor: "Major rating factor", impact: "Can affect rates by ±40%" },
      { factor: "Improving your score", impact: "Pay bills on time, keep credit utilization under 30%, dispute errors" },
    ],
    shoppingTip: "If you've had a major life event (divorce, job loss, medical emergency) that hurt your credit but you're back on track, ask your insurer about 'extraordinary life circumstance' exceptions — some carriers offer rate reviews for these situations.",
  },
  {
    slug: "should-i-bundle-home-and-auto",
    question: "Should I bundle home and auto insurance?",
    category: "Pricing",
    title: "Should I Bundle Home and Auto Insurance?",
    description: "When bundling saves money and when it doesn't.",
    answer: "Usually yes — bundling home and auto with the same carrier typically saves 10-25%. But it's not automatic. The combined cost of two policies with one carrier sometimes still exceeds two separate policies with different specialist carriers.",
    breakdown: [
      { factor: "Typical bundle discount", impact: "10-25% off both policies" },
      { factor: "Best bundle carriers", impact: "State Farm, Allstate, Nationwide, USAA" },
      { factor: "When bundling fails", impact: "If one policy is significantly overpriced, the discount won't make up for it" },
      { factor: "Always compare", impact: "Quote both 'bundle' and 'unbundled' before deciding" },
    ],
    shoppingTip: "Get quotes for both bundled and unbundled scenarios. Sometimes a specialist auto insurer + a different specialist home insurer is cheaper than even the best bundle discount. Math always wins over assumptions.",
  },
  {
    slug: "how-long-do-tickets-affect-insurance",
    question: "How long do tickets affect insurance rates?",
    category: "Driving record",
    title: "How Long Do Tickets Affect Insurance Rates?",
    description: "Speeding tickets and minor violations — how long they stay on your record and affect premiums.",
    answer: "Most minor violations affect your insurance rate for 3 years from the date of the violation. Major violations (DUI, reckless driving) can affect rates for 5-10 years and can cause non-renewal.",
    breakdown: [
      { factor: "Minor speeding ticket", impact: "Adds 10-25% for 3 years" },
      { factor: "Multiple tickets", impact: "Each adds compounding increases" },
      { factor: "At-fault accident", impact: "Adds 30-50% for 3-5 years" },
      { factor: "DUI/DWI", impact: "Doubles or triples premium for 5-10 years" },
    ],
    shoppingTip: "After your 3-year window expires, the ticket should drop off and your rates should decrease. But carriers don't always automatically lower your rate when this happens — call and ask for a rate review.",
  },
  {
    slug: "what-happens-after-accident",
    question: "What happens to my insurance after an accident?",
    category: "Claims",
    title: "What Happens to My Insurance After an Accident?",
    description: "How an accident affects your premium, what 'accident forgiveness' actually does, and when to file vs pay out-of-pocket.",
    answer: "After an at-fault accident, expect your premium to increase by 30-50% at the next renewal. The increase lasts 3-5 years. Some carriers offer 'accident forgiveness' programs that waive the first at-fault accident.",
    breakdown: [
      { factor: "At-fault accident", impact: "Premium increase of 30-50% for 3-5 years" },
      { factor: "Not-at-fault accident", impact: "Usually no rate increase, but some carriers may still raise rates" },
      { factor: "Accident forgiveness", impact: "Waives first at-fault accident for qualifying drivers" },
      { factor: "Filing small claims", impact: "Sometimes paying out-of-pocket avoids the rate hike" },
    ],
    shoppingTip: "If your repair cost is close to your deductible, consider paying out-of-pocket instead of filing a claim. A $1,200 repair with a $1,000 deductible costs you $1,000 either way — but filing the claim raises your premium for 3+ years.",
  },
  {
    slug: "best-car-insurance-for-young-drivers",
    question: "Which carriers are best for young drivers?",
    category: "Demographics",
    title: "Best Car Insurance for Young Drivers 2026",
    description: "Which carriers consistently offer the lowest rates and best programs for drivers under 25.",
    answer: "For drivers under 25, USAA (military families) consistently has the lowest rates. For everyone else, GEICO and Progressive typically offer the most competitive young-driver pricing. State Farm's Steer Clear program and Allstate's TeenSMART are strong for new drivers.",
    breakdown: [
      { factor: "USAA", impact: "Lowest rates for qualifying military family young drivers" },
      { factor: "GEICO", impact: "Competitive base rates plus Good Student discount" },
      { factor: "Progressive", impact: "Snapshot telematics can help young drivers prove safety" },
      { factor: "State Farm", impact: "Steer Clear program for under-25 with completion bonus" },
      { factor: "Allstate", impact: "TeenSMART program offers premium reduction" },
    ],
    shoppingTip: "Adding a teen driver to a parent's existing policy is usually cheaper than starting a separate young-driver policy. The parent's longer driving history and existing discounts often carry over to the teen's premium.",
  },
  {
    slug: "what-is-sr-22",
    question: "What is an SR-22?",
    category: "Legal",
    title: "What Is an SR-22? Who Needs One and Why",
    description: "SR-22 explained: when you need it, how to get one, and how long it stays on your record.",
    answer: "An SR-22 isn't an insurance policy — it's a form that proves to your state that you have the legally required liability insurance. It's typically required after DUI, reckless driving, driving without insurance, or major at-fault accidents.",
    breakdown: [
      { factor: "Trigger events", impact: "DUI/DWI, reckless driving, repeated tickets, no-insurance violations" },
      { factor: "Cost", impact: "The form itself costs $25-50, but the underlying policy is much more expensive" },
      { factor: "How long", impact: "Typically required for 3-5 years" },
      { factor: "Available from", impact: "Most major insurers, though some don't write SR-22 policies" },
    ],
    shoppingTip: "Not all carriers offer SR-22 filings. Specialty SR-22 insurance carriers like The General, Acceptance, and Dairyland typically write these policies. Once your SR-22 period ends, immediately shop with standard carriers — your rates can drop substantially.",
  },
  {
    slug: "do-i-need-rental-car-coverage",
    question: "Do I need rental car coverage on my policy?",
    category: "Coverage",
    title: "Do I Need Rental Car Coverage?",
    description: "When rental reimbursement is worth carrying and when it's not.",
    answer: "Rental reimbursement is usually inexpensive ($30-100/year) and worth carrying if your only car. It pays for a rental vehicle while your car is being repaired from a covered claim. If you have another vehicle, you may not need it.",
    breakdown: [
      { factor: "Cost to add", impact: "Typically $30-100/year" },
      { factor: "Coverage limits", impact: "Usually $30-50/day, up to $750-1,500 per claim" },
      { factor: "When you need it", impact: "Single-car households or work-from-vehicle situations" },
      { factor: "When you don't", impact: "Multi-car households with backup transportation" },
    ],
    shoppingTip: "Rental reimbursement only applies to claims that go through your collision or comprehensive coverage. If you're hit by another driver, you can typically get a rental through their liability coverage — no need to use your own rental reimbursement.",
  },
  {
    slug: "what-discounts-are-available",
    question: "What car insurance discounts are available?",
    category: "Pricing",
    title: "What Car Insurance Discounts Are Available?",
    description: "Common discounts you might not know about — and how to qualify.",
    answer: "Most insurers offer 15-25 different discount categories. You probably don't qualify for all of them, but most drivers can stack 4-7 discounts for 20-40% total savings off the base rate.",
    breakdown: [
      { factor: "Multi-policy (bundle)", impact: "10-25% off" },
      { factor: "Multi-vehicle", impact: "10-25% off" },
      { factor: "Good driver", impact: "10-25% off (3-5 years clean record)" },
      { factor: "Good student", impact: "5-15% off (B+ GPA, full-time enrollment)" },
      { factor: "Telematics", impact: "5-30% off (safe driving program)" },
      { factor: "Pay-in-full", impact: "5-10% off for paying 6 or 12 months upfront" },
      { factor: "Paperless billing", impact: "1-5% off" },
      { factor: "Defensive driving course", impact: "5-10% off (especially for seniors)" },
      { factor: "Military/veteran", impact: "5-15% off (USAA, GEICO, others)" },
      { factor: "Affiliation/employer", impact: "Varies — check your employer's benefits portal" },
    ],
    shoppingTip: "When you call for a quote, specifically ask the agent to walk through every discount category. Some discounts (like alumni associations, employer partnerships, or professional memberships) aren't automatically applied — you have to ask.",
  },
  {
    slug: "is-pay-per-mile-insurance-worth-it",
    question: "Is pay-per-mile car insurance worth it?",
    category: "Pricing",
    title: "Is Pay-Per-Mile Car Insurance Worth It?",
    description: "Usage-based and pay-per-mile programs — who saves and who doesn't.",
    answer: "If you drive less than 8,000 miles a year, pay-per-mile insurance (like Allstate Milewise, Metromile, Nationwide SmartMiles) typically saves money. If you drive over 12,000 miles a year, traditional coverage is usually cheaper.",
    breakdown: [
      { factor: "Best for low-mileage", impact: "Under 7,500 miles/year — often saves 20-40%" },
      { factor: "Pay-per-mile carriers", impact: "Allstate Milewise, Metromile, Mile Auto, Nationwide SmartMiles" },
      { factor: "How it works", impact: "Low base rate + per-mile charge tracked via app or device" },
      { factor: "Not great for", impact: "High-mileage drivers (over 12,000 miles/year)" },
    ],
    shoppingTip: "Most pay-per-mile programs cap your daily mileage charge — so a single long road trip won't bankrupt you. But before committing, calculate your annual cost based on real mileage history (not estimates) and compare to traditional carrier quotes.",
  },
  {
    slug: "how-often-should-i-shop-car-insurance",
    question: "How often should I shop my car insurance?",
    category: "Shopping",
    title: "How Often Should I Shop My Car Insurance?",
    description: "When to re-shop your auto insurance and what triggers a comparison cycle.",
    answer: "At minimum, shop your auto insurance at every renewal (every 6 or 12 months). Beyond that, shop whenever a major life event happens — marriage, divorce, moving, new car, teenager driving, retirement, or aging out of a young-driver bracket.",
    breakdown: [
      { factor: "Every renewal", impact: "Always — loyalty doesn't pay in auto insurance" },
      { factor: "After moving", impact: "Rates can change dramatically by ZIP code" },
      { factor: "After getting married", impact: "Married drivers typically get rate reductions" },
      { factor: "After a teen starts driving", impact: "Massive rate increase — shop aggressively" },
      { factor: "Age 25", impact: "Rates typically drop — make sure your carrier adjusts" },
      { factor: "After a ticket clears (3 years)", impact: "Rate should drop — call and ask for review" },
    ],
    shoppingTip: "Set a reminder for 30 days before each renewal date. Run quotes with at least 3-4 carriers using exactly the same coverage limits and deductibles. If your current carrier isn't competitive, switch — and if they are, you've confirmed you're getting a good deal.",
  },
];
