#!/usr/bin/env bash
#
# Download all carrier logos from the QuoteYeti WordPress media library
# into the repo, where review pages already expect them.
#
# URLs verified against the full media export (export-media-urls).
# Run from project root:  bash scripts/download-carrier-logos.sh
#
# NOTE: must run from a machine that can reach quoteyeti.com.

DEST="public/assets/images/carriers"
mkdir -p "$DEST"

echo "Downloading 98 carrier logos to $DEST..."
ok=0; fail=0; failed_list=""

dl() {
  # $1 = url, $2 = dest filename
  if curl -fsSL "$1" -o "$DEST/$2"; then
    echo "  ✓ $2"; ok=$((ok+1))
  else
    echo "  ✗ FAILED $2  ($1)"; fail=$((fail+1)); failed_list="$failed_list $2"
  fi
}

dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/aaa.png" "aaa.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/acuity.png" "acuity.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/aig.png" "aig.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/alfa-1.png" "alfa-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/allied.png" "allied.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/allstate.png" "allstate.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/american-family.png" "american-family.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/american-independent.png" "american-independent.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/american-national.png" "american-national.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/amica.png" "amica.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/arbella.png" "arbella.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/arrowhead-general.png" "arrowhead-general.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/auto-owners.png" "auto-owners.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/bear-river-mutual.png" "bear-river-mutual.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/bluefire.png" "bluefire.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/bristol-west.png" "bristol-west.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/california-casualty.png" "california-casualty.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/cameron.png" "cameron.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2023/03/car-insurance-net.png" "car-insurance-net.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/chubb.png" "chubb.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/cincinnati.png" "cincinnati.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/clearcover.png" "clearcover.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/co-op.png" "co-op.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/columbia.png" "columbia.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/04/cure.png" "cure.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/dairyland-1.png" "dairyland-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/direct-auto.png" "direct-auto.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/elephant-1.png" "elephant-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/emc.png" "emc.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/04/encova.png" "encova.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/esurance.png" "esurance.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2023/03/experian.png" "experian.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/farmers.png" "farmers.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2022/02/fast-insurance-rates.png" "fast-insurance-rates.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/foremost.png" "foremost.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/loya-1.png" "loya-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/freedom-national.png" "freedom-national.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/gainsco.png" "gainsco.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/geico.png" "geico.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/georgia-farm-bureau.png" "georgia-farm-bureau.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/grange-mutual.png" "grange-mutual.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/05/gulfstream.png" "gulfstream.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/hanover-1.png" "hanover-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/infinity-1.png" "infinity-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2022/02/insurance-io.png" "insurance-io.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2022/02/insurance-quotes.png" "insurance-quotes.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/05/insurify.png" "insurify.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/kemper-1.png" "kemper-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/kentucky-farm-bureau.png" "kentucky-farm-bureau.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/la-familia.png" "la-familia.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/liberty-mutual.png" "liberty-mutual.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/maine-mutual.png" "maine-mutual.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/meemic-1.png" "meemic-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/merchants.png" "merchants.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/mercury.png" "mercury.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/metlife.png" "metlife.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/metromile.png" "metromile.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/missouri-farm-bureau.png" "missouri-farm-bureau.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/motorists-mutual.png" "motorists-mutual.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/national-general.png" "national-general.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/nationwide.png" "nationwide.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/nc-farm-bureau.png" "nc-farm-bureau.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/05/new-jersey-skylands.png" "new-jersey-skylands.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/njm-1.png" "njm-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2022/02/official-car-insurance.png" "official-car-insurance.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/otto.png" "otto.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/pekin.png" "pekin.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/penn-national.png" "penn-national.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/pioneer-state.png" "pioneer-state.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/plymouth-rock.png" "plymouth-rock.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/progressive.png" "progressive.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/05/pronto.png" "pronto.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/08/provide.png" "provide.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/root-1.png" "root-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/safeauto.png" "safeauto.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/safeco.png" "safeco.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/safety-1.png" "safety-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/safeway.png" "safeway.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/secura.png" "secura.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2023/02/security-national.png" "security-national.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/selective.png" "selective.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/sentry.png" "sentry.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/shelter.png" "shelter.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/state-auto.png" "state-auto.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/state-farm.png" "state-farm.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/texas-farm-bureau.png" "texas-farm-bureau.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/the-general.png" "the-general.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/the-hartford.png" "the-hartford.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/titan-1.png" "titan-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/travelers-1.png" "travelers-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2023/03/ultimate-insurance.png" "ultimate-insurance.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/unique-car.png" "unique-car.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/usaa.png" "usaa.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/usagencies.png" "usagencies.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/victoria.png" "victoria.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/wawanesa-1.png" "wawanesa-1.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/western-national.png" "western-national.png"
dl "https://www.quoteyeti.com/wp-content/uploads/2021/09/westfield.png" "westfield.png"

echo ""
echo "──────────────────────────────────────────"
echo "  Done: $ok succeeded, $fail failed (of 98)"
if [ "$fail" -gt 0 ]; then
  echo "  Failed:$failed_list"
  echo "  Check those URLs against your media library, then re-run."
else
  echo "  All logos downloaded. Next:"
  echo "    git add public/assets/images/carriers/"
  echo "    git commit -m \"Add carrier logos from WordPress media library\""
fi
echo "  Files now in $DEST: $(ls -1 \"$DEST\" | wc -l)"
echo "──────────────────────────────────────────"
