#!/usr/bin/env bash
# Download all 99 carrier logos from the WordPress media library.
# Run from project root: bash scripts/download-carrier-logos.sh
set -e
DEST="public/assets/images/carriers"
mkdir -p "$DEST"
echo "Downloading 99 carrier logos to $DEST..."

curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/04/cure.png" -o "$DEST/cure.png" && echo "  ✓ cure.png" || echo "  ✗ FAILED cure.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/04/encova.png" -o "$DEST/encova.png" && echo "  ✓ encova.png" || echo "  ✗ FAILED encova.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/05/gulfstream.png" -o "$DEST/gulfstream.png" && echo "  ✓ gulfstream.png" || echo "  ✗ FAILED gulfstream.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/05/new-jersey-skylands.png" -o "$DEST/new-jersey-skylands.png" && echo "  ✓ new-jersey-skylands.png" || echo "  ✗ FAILED new-jersey-skylands.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/05/pronto.png" -o "$DEST/pronto.png" && echo "  ✓ pronto.png" || echo "  ✗ FAILED pronto.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/05/insurify.png" -o "$DEST/insurify.png" && echo "  ✓ insurify.png" || echo "  ✗ FAILED insurify.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/08/provide.png" -o "$DEST/provide.png" && echo "  ✓ provide.png" || echo "  ✗ FAILED provide.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/aaa.png" -o "$DEST/aaa.png" && echo "  ✓ aaa.png" || echo "  ✗ FAILED aaa.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/acuity.png" -o "$DEST/acuity.png" && echo "  ✓ acuity.png" || echo "  ✗ FAILED acuity.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/aig.png" -o "$DEST/aig.png" && echo "  ✓ aig.png" || echo "  ✗ FAILED aig.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/allstate.png" -o "$DEST/allstate.png" && echo "  ✓ allstate.png" || echo "  ✗ FAILED allstate.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/american-family.png" -o "$DEST/american-family.png" && echo "  ✓ american-family.png" || echo "  ✗ FAILED american-family.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/amica.png" -o "$DEST/amica.png" && echo "  ✓ amica.png" || echo "  ✗ FAILED amica.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/arbella.png" -o "$DEST/arbella.png" && echo "  ✓ arbella.png" || echo "  ✗ FAILED arbella.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/alfa-1.png" -o "$DEST/alfa-1.png" && echo "  ✓ alfa-1.png" || echo "  ✗ FAILED alfa-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/bear-river-mutual.png" -o "$DEST/bear-river-mutual.png" && echo "  ✓ bear-river-mutual.png" || echo "  ✗ FAILED bear-river-mutual.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/bristol-west.png" -o "$DEST/bristol-west.png" && echo "  ✓ bristol-west.png" || echo "  ✗ FAILED bristol-west.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/allied.png" -o "$DEST/allied.png" && echo "  ✓ allied.png" || echo "  ✗ FAILED allied.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/american-independent.png" -o "$DEST/american-independent.png" && echo "  ✓ american-independent.png" || echo "  ✗ FAILED american-independent.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/american-national.png" -o "$DEST/american-national.png" && echo "  ✓ american-national.png" || echo "  ✗ FAILED american-national.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/arrowhead-general.png" -o "$DEST/arrowhead-general.png" && echo "  ✓ arrowhead-general.png" || echo "  ✗ FAILED arrowhead-general.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/auto-owners.png" -o "$DEST/auto-owners.png" && echo "  ✓ auto-owners.png" || echo "  ✗ FAILED auto-owners.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/california-casualty.png" -o "$DEST/california-casualty.png" && echo "  ✓ california-casualty.png" || echo "  ✗ FAILED california-casualty.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/cameron.png" -o "$DEST/cameron.png" && echo "  ✓ cameron.png" || echo "  ✗ FAILED cameron.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/chubb.png" -o "$DEST/chubb.png" && echo "  ✓ chubb.png" || echo "  ✗ FAILED chubb.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/cincinnati.png" -o "$DEST/cincinnati.png" && echo "  ✓ cincinnati.png" || echo "  ✗ FAILED cincinnati.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/clearcover.png" -o "$DEST/clearcover.png" && echo "  ✓ clearcover.png" || echo "  ✗ FAILED clearcover.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/columbia.png" -o "$DEST/columbia.png" && echo "  ✓ columbia.png" || echo "  ✗ FAILED columbia.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/co-op.png" -o "$DEST/co-op.png" && echo "  ✓ co-op.png" || echo "  ✗ FAILED co-op.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/dairyland-1.png" -o "$DEST/dairyland-1.png" && echo "  ✓ dairyland-1.png" || echo "  ✗ FAILED dairyland-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/direct-auto.png" -o "$DEST/direct-auto.png" && echo "  ✓ direct-auto.png" || echo "  ✗ FAILED direct-auto.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/elephant-1.png" -o "$DEST/elephant-1.png" && echo "  ✓ elephant-1.png" || echo "  ✗ FAILED elephant-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/emc.png" -o "$DEST/emc.png" && echo "  ✓ emc.png" || echo "  ✗ FAILED emc.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/esurance.png" -o "$DEST/esurance.png" && echo "  ✓ esurance.png" || echo "  ✗ FAILED esurance.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/farmers.png" -o "$DEST/farmers.png" && echo "  ✓ farmers.png" || echo "  ✗ FAILED farmers.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/foremost.png" -o "$DEST/foremost.png" && echo "  ✓ foremost.png" || echo "  ✗ FAILED foremost.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/freedom-national.png" -o "$DEST/freedom-national.png" && echo "  ✓ freedom-national.png" || echo "  ✗ FAILED freedom-national.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/gainsco.png" -o "$DEST/gainsco.png" && echo "  ✓ gainsco.png" || echo "  ✗ FAILED gainsco.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/geico.png" -o "$DEST/geico.png" && echo "  ✓ geico.png" || echo "  ✗ FAILED geico.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/georgia-farm-bureau.png" -o "$DEST/georgia-farm-bureau.png" && echo "  ✓ georgia-farm-bureau.png" || echo "  ✗ FAILED georgia-farm-bureau.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/grange-mutual.png" -o "$DEST/grange-mutual.png" && echo "  ✓ grange-mutual.png" || echo "  ✗ FAILED grange-mutual.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/hanover-1.png" -o "$DEST/hanover-1.png" && echo "  ✓ hanover-1.png" || echo "  ✗ FAILED hanover-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/infinity-1.png" -o "$DEST/infinity-1.png" && echo "  ✓ infinity-1.png" || echo "  ✗ FAILED infinity-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/kemper-1.png" -o "$DEST/kemper-1.png" && echo "  ✓ kemper-1.png" || echo "  ✗ FAILED kemper-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/kentucky-farm-bureau.png" -o "$DEST/kentucky-farm-bureau.png" && echo "  ✓ kentucky-farm-bureau.png" || echo "  ✗ FAILED kentucky-farm-bureau.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/liberty-mutual.png" -o "$DEST/liberty-mutual.png" && echo "  ✓ liberty-mutual.png" || echo "  ✗ FAILED liberty-mutual.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/loya-1.png" -o "$DEST/loya-1.png" && echo "  ✓ loya-1.png" || echo "  ✗ FAILED loya-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/meemic-1.png" -o "$DEST/meemic-1.png" && echo "  ✓ meemic-1.png" || echo "  ✗ FAILED meemic-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/merchants.png" -o "$DEST/merchants.png" && echo "  ✓ merchants.png" || echo "  ✗ FAILED merchants.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/mercury.png" -o "$DEST/mercury.png" && echo "  ✓ mercury.png" || echo "  ✗ FAILED mercury.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/metlife.png" -o "$DEST/metlife.png" && echo "  ✓ metlife.png" || echo "  ✗ FAILED metlife.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/metromile.png" -o "$DEST/metromile.png" && echo "  ✓ metromile.png" || echo "  ✗ FAILED metromile.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/missouri-farm-bureau.png" -o "$DEST/missouri-farm-bureau.png" && echo "  ✓ missouri-farm-bureau.png" || echo "  ✗ FAILED missouri-farm-bureau.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/maine-mutual.png" -o "$DEST/maine-mutual.png" && echo "  ✓ maine-mutual.png" || echo "  ✗ FAILED maine-mutual.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/motorists-mutual.png" -o "$DEST/motorists-mutual.png" && echo "  ✓ motorists-mutual.png" || echo "  ✗ FAILED motorists-mutual.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/bluefire.png" -o "$DEST/bluefire.png" && echo "  ✓ bluefire.png" || echo "  ✗ FAILED bluefire.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/national-general.png" -o "$DEST/national-general.png" && echo "  ✓ national-general.png" || echo "  ✗ FAILED national-general.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/nationwide.png" -o "$DEST/nationwide.png" && echo "  ✓ nationwide.png" || echo "  ✗ FAILED nationwide.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/nc-farm-bureau.png" -o "$DEST/nc-farm-bureau.png" && echo "  ✓ nc-farm-bureau.png" || echo "  ✗ FAILED nc-farm-bureau.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/njm-1.png" -o "$DEST/njm-1.png" && echo "  ✓ njm-1.png" || echo "  ✗ FAILED njm-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/pekin.png" -o "$DEST/pekin.png" && echo "  ✓ pekin.png" || echo "  ✗ FAILED pekin.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/penn-national.png" -o "$DEST/penn-national.png" && echo "  ✓ penn-national.png" || echo "  ✗ FAILED penn-national.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/pioneer-state.png" -o "$DEST/pioneer-state.png" && echo "  ✓ pioneer-state.png" || echo "  ✗ FAILED pioneer-state.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/plymouth-rock.png" -o "$DEST/plymouth-rock.png" && echo "  ✓ plymouth-rock.png" || echo "  ✗ FAILED plymouth-rock.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/progressive.png" -o "$DEST/progressive.png" && echo "  ✓ progressive.png" || echo "  ✗ FAILED progressive.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/root-1.png" -o "$DEST/root-1.png" && echo "  ✓ root-1.png" || echo "  ✗ FAILED root-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/safeauto.png" -o "$DEST/safeauto.png" && echo "  ✓ safeauto.png" || echo "  ✗ FAILED safeauto.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/safeco.png" -o "$DEST/safeco.png" && echo "  ✓ safeco.png" || echo "  ✗ FAILED safeco.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/safety-1.png" -o "$DEST/safety-1.png" && echo "  ✓ safety-1.png" || echo "  ✗ FAILED safety-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/safeway.png" -o "$DEST/safeway.png" && echo "  ✓ safeway.png" || echo "  ✗ FAILED safeway.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/titan-1.png" -o "$DEST/titan-1.png" && echo "  ✓ titan-1.png" || echo "  ✗ FAILED titan-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/secura.png" -o "$DEST/secura.png" && echo "  ✓ secura.png" || echo "  ✗ FAILED secura.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/travelers-1.png" -o "$DEST/travelers-1.png" && echo "  ✓ travelers-1.png" || echo "  ✗ FAILED travelers-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/selective.png" -o "$DEST/selective.png" && echo "  ✓ selective.png" || echo "  ✗ FAILED selective.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/unique-car.png" -o "$DEST/unique-car.png" && echo "  ✓ unique-car.png" || echo "  ✗ FAILED unique-car.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/usaa.png" -o "$DEST/usaa.png" && echo "  ✓ usaa.png" || echo "  ✗ FAILED usaa.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/sentry.png" -o "$DEST/sentry.png" && echo "  ✓ sentry.png" || echo "  ✗ FAILED sentry.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/shelter.png" -o "$DEST/shelter.png" && echo "  ✓ shelter.png" || echo "  ✗ FAILED shelter.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/state-auto.png" -o "$DEST/state-auto.png" && echo "  ✓ state-auto.png" || echo "  ✗ FAILED state-auto.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/victoria.png" -o "$DEST/victoria.png" && echo "  ✓ victoria.png" || echo "  ✗ FAILED victoria.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/state-farm.png" -o "$DEST/state-farm.png" && echo "  ✓ state-farm.png" || echo "  ✗ FAILED state-farm.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/wawanesa-1.png" -o "$DEST/wawanesa-1.png" && echo "  ✓ wawanesa-1.png" || echo "  ✗ FAILED wawanesa-1.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/texas-farm-bureau.png" -o "$DEST/texas-farm-bureau.png" && echo "  ✓ texas-farm-bureau.png" || echo "  ✗ FAILED texas-farm-bureau.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/the-general.png" -o "$DEST/the-general.png" && echo "  ✓ the-general.png" || echo "  ✗ FAILED the-general.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/western-national.png" -o "$DEST/western-national.png" && echo "  ✓ western-national.png" || echo "  ✗ FAILED western-national.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/westfield.png" -o "$DEST/westfield.png" && echo "  ✓ westfield.png" || echo "  ✗ FAILED westfield.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/the-hartford.png" -o "$DEST/the-hartford.png" && echo "  ✓ the-hartford.png" || echo "  ✗ FAILED the-hartford.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/otto.png" -o "$DEST/otto.png" && echo "  ✓ otto.png" || echo "  ✗ FAILED otto.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/usagencies.png" -o "$DEST/usagencies.png" && echo "  ✓ usagencies.png" || echo "  ✗ FAILED usagencies.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2021/09/la-familia.png" -o "$DEST/la-familia.png" && echo "  ✓ la-familia.png" || echo "  ✗ FAILED la-familia.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2022/02/official-car-insurance.png" -o "$DEST/official-car-insurance.png" && echo "  ✓ official-car-insurance.png" || echo "  ✗ FAILED official-car-insurance.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2022/02/insurance-io.png" -o "$DEST/insurance-io.png" && echo "  ✓ insurance-io.png" || echo "  ✗ FAILED insurance-io.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2022/02/fast-insurance-rates.png" -o "$DEST/fast-insurance-rates.png" && echo "  ✓ fast-insurance-rates.png" || echo "  ✗ FAILED fast-insurance-rates.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2022/02/insurance-quotes.png" -o "$DEST/insurance-quotes.png" && echo "  ✓ insurance-quotes.png" || echo "  ✗ FAILED insurance-quotes.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2023/02/security-national.png" -o "$DEST/security-national.png" && echo "  ✓ security-national.png" || echo "  ✗ FAILED security-national.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2023/03/experian.png" -o "$DEST/experian.png" && echo "  ✓ experian.png" || echo "  ✗ FAILED experian.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2023/03/ultimate-insurance.png" -o "$DEST/ultimate-insurance.png" && echo "  ✓ ultimate-insurance.png" || echo "  ✗ FAILED ultimate-insurance.png"
curl -fsSL "https://www.quoteyeti.com/wp-content/uploads/2023/03/car-insurance-net.png" -o "$DEST/car-insurance-net.png" && echo "  ✓ car-insurance-net.png" || echo "  ✗ FAILED car-insurance-net.png"

echo "Done. Run: ls -la $DEST"